a = int(input())

if a == 10:print("1")
if a == 9:print("1")
if a == 8:print("2")
if a == 7:print("2")
if a == 6:print("3")
if a == 5:print("3")
if a == 4:print("3")
if a == 3:print("2")
if a == 2:print("2")
if a == 1:print("1")
